PostFromEssential<>yes
Z2H<>yes
RAT_ID<>ALL
CommentNotes<>
PostTextEssential<>yes
AdminHelperID<>
Photo_Host_Original<>
CommentColor<>#B22222
AdminDoor<>no
SprtLimit<>4096
AdmML<>
Logo_i<>
AdminHelperML<>
BQ2P<>no
ApproveComment<>yes
AdminHelper<>no
PhotoWidth<>144
SprtStr<><br />,<br>,</p>
Photo_Host_Replace<>localhost
Logo_o<>
CatDescReplace<>no
LnkColor<>#0F314E
DT<>d
Dscrptn<>no
PostMailEssential<>no
Blog_ID<>4
RecentComment<>10
VlnkColor<>#71BBE5
MyArcURL<>
DispNum<>10
AlnkColor<>#0F314E
BqColor<>#008000
IndividualCatLabelDisp<>no
RIT_ID<>ALL
TitleColor<>71BBE5
AuthorName<>
MT_DIR<>/virtual/touon/public_html/sachigiku.com/
BgColor<>#FFFFFF
TbColor<>#B22222
AdmNM<>
ImageAutoReduce<>yes
IndividualAuthorDisp<>no
RecentTB<>5
CatDescSort<>none
AdminPassword<>1341i
MyName<>mt4i.cgi
Ainori<>no
TxtColor<>#000000
PngWidth<>48
AdminHelperNM<>
ExitChtmlTrans<>·ÈÂÓÂÐ±þ
AccessKey<>yes
